version: "3"
services:
  zookeeper:
    image: kczulko/mesos-flink-1.2.1:sshpasswordless
    command: /root/zookeeper-startup.sh
    volumes:
      - ./zoo.cfg:/opt/flink-1.2.1/conf/zoo.cfg
      - ./slaves:/opt/flink-1.2.1/conf/slaves
      - ./slaves:/opt/flink-1.2.1/conf/masters
      - ./sshconfig:/root/.ssh/config
      - ./flink-conf.yaml:/opt/flink-1.2.1/conf/flink-conf.yaml
      - ./zookeeper-startup.sh:/root/zookeeper-startup.sh
  zk-gui:
    image: tobilg/zookeeper-webui
    environment:
      - ZK_DEFAULT_NODE=zookeeper:2181
    ports:
      - "8080:8080"
  master1:
    image: kczulko/mesos-flink-1.2.1:sshpasswordless
    command: "/root/startup.sh"
    volumes:
      - ./zoo.cfg:/opt/flink-1.2.1/conf/zoo.cfg
      - ./slaves:/opt/flink-1.2.1/conf/slaves
      - ./slaves:/opt/flink-1.2.1/conf/masters
      - ./sshconfig:/root/.ssh/config
      - ./startup.sh:/root/startup.sh
      - ./flink-conf.yaml:/opt/flink-1.2.1/conf/flink-conf.yaml
    depends_on:
      - zookeeper
#  master2:
#    image: kczulko/mesos-flink-1.2.1:sshpasswordless
#    command: "/root/startup.sh"
#    ports:
#      - "8082:8081"
#    volumes:
#      - ./slaves:/opt/flink-1.2.1/conf/slaves
#      - ./slaves:/opt/flink-1.2.1/conf/masters
#      - ./sshconfig:/root/.ssh/config
#      - ./startup.sh:/root/startup.sh
#      - ./flink-conf.yaml:/opt/flink-1.2.1/conf/flink-conf.yaml
#    depends_on:
#      - zookeeper
  slave1:
    image: kczulko/mesos-flink-1.2.1:sshpasswordless
    volumes:
      - ./zoo.cfg:/opt/flink-1.2.1/conf/zoo.cfg
      - ./slaves:/opt/flink-1.2.1/conf/slaves
      - ./slaves:/opt/flink-1.2.1/conf/masters
      - ./sshconfig:/root/.ssh/config
      - ./startup.sh:/root/startup.sh
      - ./flink-conf.yaml:/opt/flink-1.2.1/conf/flink-conf.yaml
  slave2:
    image: kczulko/mesos-flink-1.2.1:sshpasswordless
    volumes:
      - ./zoo.cfg:/opt/flink-1.2.1/conf/zoo.cfg
      - ./slaves:/opt/flink-1.2.1/conf/slaves
      - ./slaves:/opt/flink-1.2.1/conf/masters
      - ./sshconfig:/root/.ssh/config
      - ./startup.sh:/root/startup.sh
      - ./flink-conf.yaml:/opt/flink-1.2.1/conf/flink-conf.yaml

