version: "2.1"
services:
  master:
    image: kczulko/mesos-flink-1.2.1:sshpasswordless
    command: "/root/startup.sh"
    ports:
      - "8081:8081"
    volumes:
      - ./slaves:/opt/flink-1.2.1/conf/slaves
      - ./sshconfig:/root/.ssh/config
      - ./startup.sh:/root/startup.sh
      - ./flink-conf.yaml:/opt/flink-1.2.1/conf/flink-conf.yaml
  slave1:
    image: kczulko/mesos-flink-1.2.1:sshpasswordless
    volumes:
      - ./flink-conf.yaml:/opt/flink-1.2.1/conf/flink-conf.yaml
  slave2:
    image: kczulko/mesos-flink-1.2.1:sshpasswordless
    volumes:
      - ./flink-conf.yaml:/opt/flink-1.2.1/conf/flink-conf.yaml

